naif:
	ocamlopt parser.ml ARN.ml satsolver_naif.ml -o satsolver_naif
quine: 
	ocamlopt parser.ml ARN.ml dico.ml satsolver.ml -o satsolver
fnc:
	ocamlopt parser.ml ARN.ml dico.ml satsolver_fnc.ml -o satsolver_fnc
